baseURL = "https://www.irohaka.com/"
title = "イロハカの自転車日記"

languageCode = "ja-jp"
hasCJKLanguage = true
theme = "DoNormal"
dateFormat = "2006年01月02日"
disqusShortname = "irohaka"

[Params]
    author = "IROHAKA"
    images = ["images/featured.jpg"]
    description ="イロハカの自転車と旅行のブログです。"
    amazonJpAffiliate = "irohaka-22"
    tags = "自転車, ブログ"
    

[outputs]
  page = ["HTML" , "RSS"]
  Home = ["HTML" , "RSS"]

disqusShortname = "irohaka-netlify-com"

[taxonomies]
    tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false